#!/bin/bash

# Output CSV file name
output_file="command_output.csv"

# Create CSV file and add header
printf "Server IP,Ping 1.1.1.2,Ping 1.2.3.4,Telnet 1.2.3.4 80,Telnet 1.2.3.4 8443\n" > "$output_file"

# Read server IP addresses from a text file
server_file="servers.txt"
while IFS= read -r server_ip; do
    echo "Executing commands on $server_ip"

    # Execute commands using SSH with passwordless authentication
    ssh -p 77 -o StrictHostKeyChecking=no -o ConnectTimeout=5 sysadm@$server_ip << EOF

        # Command 1: Ping 1.1.1.2
        echo "Running: Ping 1.1.1.2"
        ping_output_1_1_1_2=$(ping 1.1.1.2 | tr -s ' ' | cut -d ' ' -f 8-)
        
        # Command 2: Ping 1.2.3.4
        echo "Running: Ping 1.2.3.4"
        ping_output_1_2_3_4=$(ping 1.2.3.4 | tr -s ' ' | cut -d ' ' -f 8-)

        # Command 3: Telnet 1.2.3.4 80
        echo "Running: Telnet 1.2.3.4 80"
        telnet_output_80=$(telnet 1.2.3.4 80 | tr -s ' ' | cut -d ' ' -f 2-)

        # Command 4: Telnet 1.2.3.4 8443
        echo "Running: Telnet 1.2.3.4 8443"
        telnet_output_8443=$(telnet 1.2.3.4 8443 | tr -s ' ' | cut -d ' ' -f 2-)

        printf "%s,%s,%s,%s,%s\n" "$server_ip" "$ping_output_1_1_1_2" "$ping_output_1_2_3_4" "$telnet_output_80" "$telnet_output_8443" >> "$output_file"

EOF

    echo "Commands executed on $server_ip"
done < "$server_file"

echo "Command output saved in $output_file"
